<a href="https://colab.research.google.com/github/Aarthykannan/ak/blob/main/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import tensorflow as tf


In [3]:
path = '/content/shakespeare.txt'

In [4]:
text = open(path,'r').read()

In [5]:
text[:500]

"\n                     1\n  From fairest creatures we desire increase,\n  That thereby beauty's rose might never die,\n  But as the riper should by time decease,\n  His tender heir might bear his memory:\n  But thou contracted to thine own bright eyes,\n  Feed'st thy light's flame with self-substantial fuel,\n  Making a famine where abundance lies,\n  Thy self thy foe, to thy sweet self too cruel:\n  Thou that art now the world's fresh ornament,\n  And only herald to the gaudy spring,\n  Within thine own bu"

In [7]:
vocab = sorted(set(text))
vocab    # all unique char

['\n',
 ' ',
 '!',
 '"',
 '&',
 "'",
 '(',
 ')',
 ',',
 '-',
 '.',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '<',
 '>',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 '[',
 ']',
 '_',
 '`',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '|',
 '}']

In [8]:
len(vocab)

84

In [9]:
# all char index

char_ind = {char:ind for ind,char in enumerate(vocab)}
char_ind['h']

63

In [10]:
ind_char = np.array(vocab)
ind_char[80]

'y'

In [11]:
encod_txt = np.array([char_ind[c] for c in text])
encod_txt.shape

(5445609,)

In [12]:
text[:500]

"\n                     1\n  From fairest creatures we desire increase,\n  That thereby beauty's rose might never die,\n  But as the riper should by time decease,\n  His tender heir might bear his memory:\n  But thou contracted to thine own bright eyes,\n  Feed'st thy light's flame with self-substantial fuel,\n  Making a famine where abundance lies,\n  Thy self thy foe, to thy sweet self too cruel:\n  Thou that art now the world's fresh ornament,\n  And only herald to the gaudy spring,\n  Within thine own bu"

In [13]:
encod_txt[:500]

array([ 0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1, 12,  0,  1,  1, 31, 73, 70, 68,  1, 61, 56, 64,
       73, 60, 74, 75,  1, 58, 73, 60, 56, 75, 76, 73, 60, 74,  1, 78, 60,
        1, 59, 60, 74, 64, 73, 60,  1, 64, 69, 58, 73, 60, 56, 74, 60,  8,
        0,  1,  1, 45, 63, 56, 75,  1, 75, 63, 60, 73, 60, 57, 80,  1, 57,
       60, 56, 76, 75, 80,  5, 74,  1, 73, 70, 74, 60,  1, 68, 64, 62, 63,
       75,  1, 69, 60, 77, 60, 73,  1, 59, 64, 60,  8,  0,  1,  1, 27, 76,
       75,  1, 56, 74,  1, 75, 63, 60,  1, 73, 64, 71, 60, 73,  1, 74, 63,
       70, 76, 67, 59,  1, 57, 80,  1, 75, 64, 68, 60,  1, 59, 60, 58, 60,
       56, 74, 60,  8,  0,  1,  1, 33, 64, 74,  1, 75, 60, 69, 59, 60, 73,
        1, 63, 60, 64, 73,  1, 68, 64, 62, 63, 75,  1, 57, 60, 56, 73,  1,
       63, 64, 74,  1, 68, 60, 68, 70, 73, 80, 21,  0,  1,  1, 27, 76, 75,
        1, 75, 63, 70, 76,  1, 58, 70, 69, 75, 73, 56, 58, 75, 60, 59,  1,
       75, 70,  1, 75, 63

In [15]:
# create batches
seq_len = 120
total_seq = len(text)//(seq_len +1)  # // to get in whole decimal
total_seq

45005

In [17]:
char_data = tf.data.Dataset.from_tensor_slices(encod_txt)

In [18]:
type(char_data)

tensorflow.python.data.ops.from_tensor_slices_op._TensorSliceDataset

In [21]:
seq = char_data.batch(seq_len+1,drop_remainder = True) # here // other deciaml points remove

In [22]:
def create_seq_target(seq):
  ip_txt = seq[:-1]
  tar_txt = seq[1:]
  return ip_txt,tar_txt

In [26]:
dataset = seq.map(create_seq_target)

In [25]:
for ip_txt,tar_txt in datasets.take(1):
  print(ip_txt.numpy())
  print(''.join(ind_char[ip_txt.numpy()]))
  print('/n')
  print(tar_txt.numpy())
  print(''.join(ind_char[tar_txt.numpy()]))

[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0
  1  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74
  1 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45
 63 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74
 60  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75]

                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But
/n
[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0  1
  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74  1
 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45 63
 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74 60
  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75  1]
                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But 


In [27]:
# generate batch size

batch_size = 128
buffer_size = 10000
dataset = dataset.shuffle(buffer_size).batch(batch_size,drop_remainder = True)
dataset

<_BatchDataset element_spec=(TensorSpec(shape=(128, 120), dtype=tf.int64, name=None), TensorSpec(shape=(128, 120), dtype=tf.int64, name=None))>

In [28]:
vocab_size = len(vocab)
vocab_size

84

In [29]:
embed_dim = 64
rnn_neu = 1026

In [31]:
from tensorflow.keras.losses import sparse_categorical_crossentropy as scc
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM,Embedding,Dense,Dropout,GRU

In [32]:
def sparse_loss(y_true,y_pred):
  return scc(y_true,y_pred,from_logits=True)

In [39]:
def create_model(vocab_size,embed_dim,rnn_neu,batch_size = 1):
  model = Sequential()
  model.add(Embedding(vocab_size,embed_dim,batch_input_shape =[batch_size,None]))
  model.add(GRU(rnn_neu,return_sequences=True,stateful=True,recurrent_initializer='glorot_uniform'))
  model.add(Dense(vocab_size))
  model.compile(optimizer = 'adam',loss='sparse_loss')
  return model

In [40]:
model = create_model(vocab_size=vocab_size,embed_dim=embed_dim,rnn_neu=rnn_neu,batch_size=batch_size)

In [41]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (128, None, 64)           5376      
                                                                 
 gru_1 (GRU)                 (128, None, 1026)         3361176   
                                                                 
 dense_1 (Dense)             (128, None, 84)           86268     
                                                                 
Total params: 3,452,820
Trainable params: 3,452,820
Non-trainable params: 0
_________________________________________________________________


In [43]:
# Train the model
for ip_eg,tar_eg in dataset.take(1):
  eg_pred = model(ip_eg)
eg_pred.shape

TensorShape([128, 120, 84])

In [44]:
eg_pred[0]

<tf.Tensor: shape=(120, 84), dtype=float32, numpy=
array([[ 0.01624654, -0.00074363,  0.00233665, ..., -0.0023655 ,
         0.00060957, -0.01162981],
       [ 0.01471808,  0.00164185,  0.00278377, ..., -0.00336357,
         0.00140426, -0.01191324],
       [ 0.00953329,  0.00136003, -0.00049821, ...,  0.0031175 ,
         0.00149064, -0.00693263],
       ...,
       [-0.00179395,  0.0006824 ,  0.00110862, ...,  0.00733825,
         0.00016177, -0.0015899 ],
       [ 0.00628918, -0.00060321,  0.00111935, ...,  0.00424478,
         0.00024748, -0.00627991],
       [ 0.00693843, -0.00303775, -0.00362401, ..., -0.00309264,
        -0.00091497, -0.00785   ]], dtype=float32)>

In [45]:
sample_ind = tf.random.categorical(eg_pred[0],num_samples=1)
sample_ind

<tf.Tensor: shape=(120, 1), dtype=int64, numpy=
array([[21],
       [57],
       [73],
       [ 4],
       [ 2],
       [58],
       [71],
       [72],
       [70],
       [77],
       [11],
       [10],
       [68],
       [ 4],
       [ 7],
       [60],
       [ 9],
       [41],
       [83],
       [18],
       [13],
       [29],
       [54],
       [27],
       [74],
       [75],
       [54],
       [11],
       [75],
       [16],
       [46],
       [12],
       [ 7],
       [65],
       [51],
       [55],
       [22],
       [74],
       [ 9],
       [80],
       [30],
       [31],
       [ 2],
       [12],
       [ 5],
       [ 5],
       [29],
       [37],
       [38],
       [18],
       [42],
       [11],
       [82],
       [34],
       [35],
       [45],
       [40],
       [82],
       [37],
       [15],
       [31],
       [10],
       [72],
       [72],
       [18],
       [15],
       [ 1],
       [10],
       [29],
       [58],
       [36],
       [44],
       [48],
   

In [46]:
sample_ind = tf.squeeze(sample_ind,axis=1).numpy()
sample_ind

array([21, 57, 73,  4,  2, 58, 71, 72, 70, 77, 11, 10, 68,  4,  7, 60,  9,
       41, 83, 18, 13, 29, 54, 27, 74, 75, 54, 11, 75, 16, 46, 12,  7, 65,
       51, 55, 22, 74,  9, 80, 30, 31,  2, 12,  5,  5, 29, 37, 38, 18, 42,
       11, 82, 34, 35, 45, 40, 82, 37, 15, 31, 10, 72, 72, 18, 15,  1, 10,
       29, 58, 36, 44, 48, 59, 63, 79, 78, 29, 60, 79, 76,  4, 80, 28, 34,
       13, 79, 34,  7,  5, 30, 17, 39, 26,  2, 83, 36, 41, 59, 61, 74,  4,
       83, 28, 63, 34, 68, 35,  7, 60, 20,  7, 59, 59, 35,  1, 60, 19, 61,
       31])

In [47]:
ind_char[sample_ind]

array([':', 'b', 'r', '&', '!', 'c', 'p', 'q', 'o', 'v', '0', '.', 'm',
       '&', ')', 'e', '-', 'P', '}', '7', '2', 'D', '_', 'B', 's', 't',
       '_', '0', 't', '5', 'U', '1', ')', 'j', 'Z', '`', ';', 's', '-',
       'y', 'E', 'F', '!', '1', "'", "'", 'D', 'L', 'M', '7', 'Q', '0',
       '|', 'I', 'J', 'T', 'O', '|', 'L', '4', 'F', '.', 'q', 'q', '7',
       '4', ' ', '.', 'D', 'c', 'K', 'S', 'W', 'd', 'h', 'x', 'w', 'D',
       'e', 'x', 'u', '&', 'y', 'C', 'I', '2', 'x', 'I', ')', "'", 'E',
       '6', 'N', 'A', '!', '}', 'K', 'P', 'd', 'f', 's', '&', '}', 'C',
       'h', 'I', 'm', 'J', ')', 'e', '9', ')', 'd', 'd', 'J', ' ', 'e',
       '8', 'f', 'F'], dtype='<U1')

In [48]:
''' epochs = 30
    model.fit(dataset,epochs=epochs)'''


' epochs = 30\n    model.fit(dataset,epochs=epochs)'

In [50]:
# load model
from tensorflow.keras.models import load_model
model = create_model(vocab_size,embed_dim,rnn_neu,batch_size=1)
model.load_weights('shakespeare_gen.h5')
model.build(tf.TensorShape([1,None]))
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (1, None, 64)             5376      
                                                                 
 gru_3 (GRU)                 (1, None, 1026)           3361176   
                                                                 
 dense_3 (Dense)             (1, None, 84)             86268     
                                                                 
Total params: 3,452,820
Trainable params: 3,452,820
Non-trainable params: 0
_________________________________________________________________


In [52]:
def gen_txt(model,start_seed,gen_size=500,temp=1.0):

  num_gen = gen_size
  ip_eval = [char_ind[s] for s in start_seed]  # here flower char char_ind
  ip_eval = tf.expand_dims(ip_eval,0)     # to match format shape
  txt_gen = []
  temperature = temp
  model.reset_states()
  for i in range(num_gen):
    pred = model(ip_eval)  # pred
    pred = tf.squeeze(pred,0)   # squeese
    pred = pred/temp
    pred_id = tf.random.categorical(pred,num_samples=1)[-1,0].numpy()
    ip_eval = tf.expand_dims([pred_id],0)
    txt_gen.append(ind_char[pred_id])
  return (start_seed+''.join(txt_gen))

In [53]:
print(gen_txt(model,'flower',gen_size=1000))

flower.
    What have you done? boot up in place that this should be so bride.
  OTHELLO. Leadnow merrily and killingly
    Loss on between the pebblesh' that was blameed, a while would have
    me
    against him, which is not enough of this arm.
  PETRUCHIO. What?
  MACBETH. Ly pains. I cannot fly the best without
    Protectors    With t back, mon Angla.
  SECTON. Ay, and my elder Haven within the visitation
    To break with this present.
  ESCALUS. Why, that's the matter
    Of barribonded proof; scorn to my friend;
    Which took them to undertake Hero, Scotland.
  MENAS. What most that be but grief is still to-morrow?
  BOTTOM. Nothing.
  JULIA. Abork';
    Nor how soon marriage bears more action.
    La N, NEDISSION, PRINCE OF YORK DUKE OF YORK
  ADAM
ENTITH PERMISSION.  ELECTRONIC AND MACHINE READABLE COPIES MAY BE
DISTRIBUTED SO LONG AS SUCH COPIES (1) ARE FOR YOUR OR OTHERS
PERSONAL USE ONLY, AND (2) ARE NOT DISTRIBUTED OR USED
COMMERCIALLY.  PROHIBITED COMMERCIAL DISTRIBUTI